version: '3'

services:
  flask:
    build: .
    container_name: flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: python main.py
    depends_on:
      - postgres
      - redis

  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgres_container
    image: postgres:14
    volumes:
      - flaskdb:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - db-conn

  redis:
    env_file:
      - ./docker/.env
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
        - redis-conn

volumes:
  flaskdb:
  redis-data:

networks:
  db-conn:
    driver: bridge
  redis-conn:
    driver: bridge