version: '2'

services:
  flask:
    build: .
    container_name: flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: python main.py
    depends_on:
      - postgres
      - redis
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:v2.33.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    env_file: ./monitoring/config.monitoring
    image: grafana/grafana:8.3.4
    ports:
      - 3000:3000

  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgres_container
    image: postgres:14
    volumes:
      - flaskdb:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - db-conn

  redis:
    env_file:
      - ./docker/.env
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
        - redis-conn

volumes:
  flaskdb:
  redis-data:

networks:
  db-conn:
    driver: bridge
  redis-conn:
    driver: bridge