version: '3'

services:
  flask:
    build: .
    container_name: flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: python manage.py runserver 0.0.0.0:5000

    depends_on:
      - redis
      - postgres

  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgres_container
    image: postgres:14
    volumes:
      - flaskdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    env_file:
      - ./docker/.env
    image: redis
    container_name: redis
    ports:
      - "6379:6379"