{
 "title": "Pokemon dashboard",
 "time": { "from": "2023-12-02T00:00:00.000Z", "to": "2023-12-04T00:00:00.000Z" },
 "panels": [
  {
   "title": "График, отображающий количество раундов по дням за последние 2 недели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(rounds) as total_rounds\r\nFROM results \r\nWHERE date >= current_date - INTERVAL '2 weeks'\r\nGROUP BY date;"
    }
   ]
  },
  {
   "title": "График, отображающий количество проведенных боев по дням за последние 2 недели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(*) as battles_count\r\nFROM results \r\nWHERE date >= current_date - INTERVAL '2 weeks'\r\nGROUP BY date;"
    }
   ]
  },
  {
   "title": "Общая статистика боев:",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS total_battles,\r\n    AVG(rounds) AS average_rounds\r\nFROM \r\n    results;"
    }
   ]
  },
  {
   "title": "Топ-5 покемонов по количеству побед",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT user_pokemon, COUNT(*) AS wins\r\nFROM results \r\nWHERE winner = user_pokemon\r\nGROUP BY user_pokemon\r\nORDER BY wins DESC\r\nLIMIT 5;"
    }
   ]
  }
 ]
}